---
# This playbook installs security tools on a Linux machine.
# Author: dfir-jesseee PRCCDC
# Date: 2025-02-23
- name: Setup Security Tools on Linux
  hosts: all
  become: yes
  tasks:
    - name: Update and Upgrade APT
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ansible
          - netexec
          - virtualenv
          - powershell-empire
          - hydra
          - burpsuite
          - hashcat
          - nikto
          - gobuster
          - docker.io
        state: present

    - name: Create Python Virtual Environment Directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/python-env"
        state: directory
        mode: '0755'

    - name: Create Virtual Environment
      ansible.builtin.command:
        cmd: virtualenv pip
        chdir: "{{ ansible_env.HOME }}/python-env"
      args:
        creates: "{{ ansible_env.HOME }}/python-env/pip/bin/activate"

    - name: Activate Virtual Environment
      ansible.builtin.shell:
        cmd: source pip/bin/activate
        chdir: "{{ ansible_env.HOME }}/python-env"

    - name: Run CEWL in Docker
      ansible.builtin.command:
        cmd: docker run -it --rm -v "${PWD}:/host" ghcr.io/digininja/cewl

    - name: Add Sublime Text Repository Key
      ansible.builtin.shell:
        cmd: wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg

    - name: Add Sublime Text Repository
      ansible.builtin.shell:
        cmd: echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list

    - name: Update APT Cache After Adding Sublime Repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Sublime Text
      ansible.builtin.apt:
        name: sublime-text
        state: present

    - name: Install Metasploit
      ansible.builtin.shell:
        cmd: |
          curl https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb > msfinstall && \
          chmod 755 msfinstall && \
          ./msfinstall
        chdir: "/tmp"
        creates: "/usr/bin/msfconsole"
